Move near cache to datastore.
openlattice/openlattice pull request #109
Opened 2021-02-01 19:44 UTC by geekbeast

2021-02-01 20:11 UTC, katherinebernstein approved these changes

2021-02-01 22:05 UTC, UnsungHero97 requested changes

2021-02-01 22:05 UTC, UnsungHero97 commented on conductor-client/src/main/kotlin/com/openlattice/hazelcast/pods/NearCachesPod.kt
> +    fun permissionsNearcCacheConfig(): NearCacheConfig? {
Please remove extra `c` between `NearCache`.

2021-02-02 20:15 UTC, makosblade submitted a review, later dismissed
So what exactly does this do aside from disabling NearCacheConfig on PermissionsMapstore? I don't see anything pulling in `NearCacheConfig` in this change or setting it on any maps

2021-02-02 22:06 UTC, geekbeast commented
> So what exactly does this do aside from disabling NearCacheConfig on PermissionsMapstore? I don't see anything pulling in `NearCacheConfig` in this change or setting it on any maps

It moves the near cache to datastore instead of conductor.

Configuration happens inside of our standard hazelcast instance configuration routines.

https://github.com/geekbeast/rhizome/blob/bb8a0740f24f8f1e147dd4c29af3fb15cd6cd357/src/main/java/com/kryptnostic/rhizome/pods/hazelcast/RegistryBasedHazelcastInstanceConfigurationPod.java#L115
https://github.com/geekbeast/rhizome/blob/bb8a0740f24f8f1e147dd4c29af3fb15cd6cd357/src/main/java/com/kryptnostic/rhizome/pods/hazelcast/BaseHazelcastInstanceConfigurationPod.java#L135

2021-02-02 22:26 UTC, makosblade commented
> > So what exactly does this do aside from disabling NearCacheConfig on PermissionsMapstore? I don't see anything pulling in `NearCacheConfig` in this change or setting it on any maps
> 
> It moves the near cache to datastore instead of conductor.
> 
> Configuration happens inside of our standard hazelcast instance configuration routines.
> 
> https://github.com/geekbeast/rhizome/blob/bb8a0740f24f8f1e147dd4c29af3fb15cd6cd357/src/main/java/com/kryptnostic/rhizome/pods/hazelcast/RegistryBasedHazelcastInstanceConfigurationPod.java#L115
> https://github.com/geekbeast/rhizome/blob/bb8a0740f24f8f1e147dd4c29af3fb15cd6cd357/src/main/java/com/kryptnostic/rhizome/pods/hazelcast/BaseHazelcastInstanceConfigurationPod.java#L135

Okay cool. It seems like this sets up a NearCache config for *all* mapstores, not just the PermissionsMapstore though. Is that intended?

2021-02-02 23:40 UTC, geekbeast commented
> > > So what exactly does this do aside from disabling NearCacheConfig on PermissionsMapstore? I don't see anything pulling in `NearCacheConfig` in this change or setting it on any maps
> > 
> > 
> > It moves the near cache to datastore instead of conductor.
> > Configuration happens inside of our standard hazelcast instance configuration routines.
> > https://github.com/geekbeast/rhizome/blob/bb8a0740f24f8f1e147dd4c29af3fb15cd6cd357/src/main/java/com/kryptnostic/rhizome/pods/hazelcast/RegistryBasedHazelcastInstanceConfigurationPod.java#L115
> > https://github.com/geekbeast/rhizome/blob/bb8a0740f24f8f1e147dd4c29af3fb15cd6cd357/src/main/java/com/kryptnostic/rhizome/pods/hazelcast/BaseHazelcastInstanceConfigurationPod.java#L135
> 
> Okay cool. It seems like this sets up a NearCache config for _all_ mapstores, not just the PermissionsMapstore though. Is that intended?

Woops nice catch. I updated to only be on permission map.

2021-02-02 23:58 UTC, katherinebernstein approved these changes

2021-02-02 23:59 UTC, UnsungHero97 approved these changes

2021-02-03 00:02 UTC, makosblade approved these changes

2021-02-03 00:43 UTC, merged